voxpupuli/puppet-borg

- metadata.json
> allow Puppet 6.x in metadata.json

- metadata.json
> allow puppetlabs/stdlib 5.x and 6.x; allow camptocamp/systemd 2.X,  allow saz/ssh 5.x

- metadata.json
> allow saz/ssh 6.x

- LICENSE
- README.md
- metadata.json
> Update documentation/README.md/metadata.json after repo migration

- templates/borg-backup.sh.epp
> backup lvm2 config if vgcfgbackup is present

- .fixtures.yml
- data/Ubuntu-16.04.yaml
- data/common.yaml
- manifests/init.pp
- manifests/install.pp
- spec/classes/init_spec.rb
- spec/spec_helper_acceptance.rb
> Add support for PPAs on Ubuntu 16.04

- templates/borg-restore.pl.epp
- templates/borg_exporter.sh.epp
> add `managed by puppet` header to templates

- metadata.json
> allow puppetlabs/vcsrepo 3.x

- CHANGELOG.md
- metadata.json
> release 1.0.1

- .github/CONTRIBUTING.md
- .msync.yml
- .sync.yml
- Gemfile
- spec/spec_helper.rb
> modulesync 2.8.0

- manifests/service.pp
> simplify systemd timer setup

- .travis.yml
- Dockerfile
- Gemfile
- Rakefile
- manifests/init.pp
- spec/spec_helper.rb
> modulesync 2.9.0

- CHANGELOG.md
- metadata.json
> release 1.1.1

- metadata.json
> Add CentOS/RedHat 8 to metadata.json

- data/common.yaml
- spec/acceptance/init_spec.rb
> Add /var/log to default includes

- metadata.json
*Some* people already use this in production, so we should test against
it.
> Add VZ 7 support

- CHANGELOG.md
- metadata.json
> Release 1.3.1

- .github/SECURITY.md
- .msync.yml
- .rubocop.yml
- .travis.yml
- Gemfile
- manifests/config.pp
- manifests/init.pp
- manifests/install.pp
- manifests/service.pp
> modulesync 3.0.0 & puppet-lint updates

- templates/borg-backup.sh.epp
> borg-backup script: mention env var for passphrase

- CHANGELOG.md
- metadata.json
> release 1.4.0

- manifests/install.pp
> dont hardcode data we have in variables as well

- manifests/install.pp
> installation: Add local bin paths to $PATH

- REFERENCE.md
- data/RedHat.yaml
- data/common.yaml
- manifests/init.pp
- manifests/install.pp
- spec/acceptance/init_spec.rb
- spec/classes/init_spec.rb
- spec/spec_helper_acceptance.rb
> Implement support for upstream cpanm management / BorgRestore: Add support for upgrades/downgrades

- spec/acceptance/init_spec.rb
On some operating systems we setup an upstream borg repo to get the
latest version. It's a good idea to validate that with a test.
> Add acceptance test to verify repo creation

- CHANGELOG.md
- metadata.json
> release 1.5.0

- manifests/init.pp
- spec/acceptance/init_spec.rb
> update borg-restore.pl 3.4.3->3.4.4

- templates/borg-backup.sh.epp
> borg-backup: Increase logging for create/prune

- CHANGELOG.md
- REFERENCE.md
- metadata.json
> release 1.6.0

- metadata.json
> Drop Fedora 22-31, add 32/33

- data/CentOS-8.yaml
- data/RedHat-8.yaml
- spec/classes/init_spec.rb
> Fix wrong package dependencies on CentOS 8

- REFERENCE.md
- manifests/config.pp
- manifests/init.pp
- spec/classes/init_spec.rb
> make ssh key type configureable

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .msync.yml
- Dockerfile
- Gemfile
- metadata.json
- spec/spec_helper_acceptance.rb
* https://github.com/voxpupuli/puppet-borg/pull/100
* https://github.com/voxpupuli/puppet-borg/pull/102
* https://github.com/voxpupuli/puppet-borg/pull/103
* https://github.com/voxpupuli/puppet-borg/pull/104
this fixes CI failures on CentOS 7 + Puppet 7
> beaker: set US locale

- metadata.json
> puppetlabs/vcsrepo: Allow 4.x & 5.x

- metadata.json
> puppet/ssh_keygen: Allow 5.x

- metadata.json
> Drop EoL Puppet 5 support; Add Puppet 7 support

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .msync.yml
- Dockerfile
- Gemfile
- metadata.json
> modulesync 4.1.0

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .msync.yml
- Dockerfile
- Gemfile
- metadata.json
* https://github.com/voxpupuli/puppet-borg/pull/100
> saz/ssh: Allow 7.x

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .msync.yml
- Dockerfile
- Gemfile
- metadata.json
- spec/spec_helper_acceptance.rb
* https://github.com/voxpupuli/puppet-borg/pull/100
* https://github.com/voxpupuli/puppet-borg/pull/102
> puppet/archive: Allow 5.x

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .msync.yml
- Dockerfile
- Gemfile
- metadata.json
- spec/spec_helper_acceptance.rb
* https://github.com/voxpupuli/puppet-borg/pull/100
* https://github.com/voxpupuli/puppet-borg/pull/102
* https://github.com/voxpupuli/puppet-borg/pull/103
> puppetlabs/apt: allow 8.x

- REFERENCE.md
- manifests/config.pp
- manifests/init.pp
- manifests/install.pp
- templates/borg-backup.sh.epp
- templates/borg-restore.cfg.epp
- templates/borg.sh.epp
> Enable user to configure the backup destination path

- metadata.json
> Add Debian 10 support

- .editorconfig
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .gitignore
- .msync.yml
- .overcommit.yml
- .pmtignore
- .rspec
- .rspec_parallel
- .rubocop.yml
- .yardopts
- Dockerfile
- Gemfile
- Rakefile
- spec/spec_helper.rb
> modulesync 4.1.0-39-gb7fda28

- templates/borg-backup.service.epp
> Start backups only if network is available

- README.md
> fix broken README.md badges

- CHANGELOG.md
- metadata.json
> Release 2.1.1

- README.md
- spec/acceptance/init_spec.rb
> Document CentOS8 requirement of PowerTools repo

- Gemfile
> puppet_metadata: Allow 1.x

- metadata.json
> saz/ssh: Allow 8.x

- .msync.yml
- Gemfile
- spec/spec_helper.rb
> modulesync 5.0.0

- .sync.yml
- Gemfile
> test new voxpupuli-test setup

- Gemfile
> Gemfile: switch back to usual voxpupuli-test release

- README.md
> Update hiera documentation in README.md

- CHANGELOG.md
- metadata.json
> Release 2.3.1

- .github/workflows/ci.yml
- .puppet-lint.rc
- .sync.yml
- Rakefile
> modulesync 5.1.0

- .fixtures.yml
- REFERENCE.md
- manifests/init.pp
- manifests/service.pp
- spec/classes/init_spec.rb
- templates/borg-backup.service.epp
> Implement support for custom unit dependencies

- CHANGELOG.md
- metadata.json
> Release 2.4.0

- metadata.json
- spec/acceptance/init_spec.rb
> saz/ssh: Allow 9.x / Fix CentOS 8 acceptance tests 

- spec/acceptance/init_spec.rb
> Implement Arch Linux acceptance testing

- .fixtures.yml
- .github/CONTRIBUTING.md
- Gemfile
> modulesync 5.2.0

- templates/borg-backup.sh.epp
> borg prune: List archives that wont be deleted

- metadata.json
> saz/ssh: Allow 10.x

- CHANGELOG.md
- REFERENCE.md
- metadata.json
> Release 3.2.0

- metadata.json
> puppet/ssh_keygen: Allow 7.x

- metadata.json
> saz/ssh: Allow 11.x

- REFERENCE.md
- data/Archlinux.yaml
- manifests/init.pp
- manifests/install.pp
- spec/acceptance/init_spec.rb
- spec/classes/init_spec.rb
> Arch Linux: Dont install perl-app-borgrestore when borg should be installed

- REFERENCE.md
- manifests/config.pp
- manifests/init.pp
- templates/borg-backup.sh.epp
> Make upload ratelimit configurable

- data/Archlinux.yaml
- manifests/install.pp
ArchLinux doesn't provide that package anymore
> ArchLinux: Remove perl-app-borgrestore

- metadata.json
Ref: https://github.com/voxpupuli/community-triage/issues/44
> saz/ssh Allow 13.x, puppetlabs/vcsrepo Allow 7.x

- data/AlmaLinux-9.yaml
- data/CentOS-9.yaml
- data/RedHat-9.yaml
- data/Rocky-9.yaml
- metadata.json
- spec/classes/init_spec.rb
> Support El9
